---
stages:
  - build

container:
  stage: build
  image: registry.hanse-merkur.de/hcp/oci/buildah
  before_script:
    - IMAGE_NAME=${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_TAG:-latest}
  script:
    - export REGISTRY_AUTH_FILE=${HOME}/auth.json
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - buildah bud -f Dockerfile -t ${IMAGE_NAME} .
    - buildah push ${IMAGE_NAME}

chart:
  image: registry.hanse-merkur.de/hcp/oci/helm
  stage: build
  script:
    - export HELM_REPO_USERNAME=$CI_REGISTRY_USER
    - export HELM_REPO_PASSWORD=$CI_REGISTRY_PASSWORD
    - helm dep up helm/cifs-flex
    - unset https_proxy http_proxy HTTP_PROXY HTTPS_PROXY
    - mkdir -p ./public
    - export no_proxy=hanse-merkur.de,localhost
    - helm repo add registry-hcp https://${CI_REGISTRY}/chartrepo/wellerl
    - helm package helm/cifs-flex --destination public
    - helm push public/cifs-flex*.tgz registry-hcp
    - rm -f public/*tgz
